steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image and push'
  args: [
    'build',
    '.',
    '-t',
    'europe-west3-docker.pkg.dev/exalted-strata-447112-s0/mlops-container-registry/dockerimage:latest',
    '-f',
    'Dockerfile'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west3-docker.pkg.dev/exalted-strata-447112-s0/mlops-container-registry/dockerimage:latest'
  ]

options:
  logging: CLOUD_LOGGING_ONLY
