steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '-t',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/mlops-container-registry/my_fastapi_app:latest',
    '-f',
    'dockerfiles/api.dockerfile',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/mlops-container-registry/my_fastapi_app:latest'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args: [
    'run',
    'deploy',
    'my-fastapi-app',
    '--image',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/mlops-container-registry/my_fastapi_app:latest',
    '--region',
    'europe-west3',
    '--platform',
    'managed',
  ]
options:
  logging: CLOUD_LOGGING_ONLY
