name: CML Workflow

on:
  pull_request:
    branches:
    - main
    paths:
    - '**/*.dvc'
    - '.dvc/**'

jobs:
  run_data_checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'
        cache-dependency-path: setup.py

    - name: Install dependencies
      working-directory: my_project
      run: |
        python -m pip install -U pip setuptools wheel
        pip install -r requirements.txt
        pip list

    - name: Set credentials path
      shell: bash
      run: |
        echo "CREDENTIALS_PATH=$RUNNER_TEMP/credentials.json" >> $GITHUB_ENV

    - name: Get data
      working-directory: my_project
      shell: bash
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_CREDENTIALS_DATA }}
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS" > "$CREDENTIALS_PATH"
        dvc remote add -d my_remote gs://dtu_mlops_osquera
        dvc remote modify my_remote  credentialpath "$CREDENTIALS_PATH"
        dvc pull -r my_remote


    - name: Pull data
      run: |
        dvc pull --no-run-cache

    - name: Check data statistics
      working-directory: my_project
      run: |
        python src/my_project/dataset_statistics.py

    - name: Check data statistics & generate report
      working-directory: my_project
      run: |
        python src/my_project/dataset_statistics.py > ../data_statistics.md
        echo '![](./mnist_images.png "MNIST images")' >> ../data_statistics.md
        echo '![](./train_label_distribution.png "Train label distribution")' >> ../data_statistics.md
        echo '![](./test_label_distribution.png "Test label distribution")' >> ../data_statistics.md

    - name: Setup cml
      uses: iterative/setup-cml@v2

    - name: Comment on PR
      working-directory: my_project
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cml comment create ../data_statistics.md --watermark-title="Data Checker"
