name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: true
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.12", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        working-directory: my_project
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.txt
          pip list


      - name: Run tests & coverage
        working-directory: my_project
        run: |
          coverage run -m pytest tests/
          coverage report -m

      - uses: iterative/setup-dvc@v1
      - name: Get data
        working-directory: my_project
        run: |
          dvc pull
        env:
            GDRIVE_CREDENTIALS_DATA: ${{ secrets.GCLOUD_CREDENTIALS_DATA }}
